language: ruby
rvm:
  - 2.0.0-p247
  - 2.1.0
  - 2.1.1
script:
  - bundle exec rake
  - bundle exec rubocop
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database rails_template_test;' -U postgres
  - bundle exec rake db:setup
