production:
  adapter: postgresql
  database: ptaatlantis_production
  username: ptaatlantis
  password: 
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  database: <%= "#{ENV['APP_IDENTIFIER']}_development" %>
  username: screenconcept
  password:
  encoding: unicode
  pool: 5
  host: localhost
  port: <%= ENV['BOXEN_POSTGRESQL_PORT'] || 5432 %>
